---
title: Papers (Theory and Methods)
---

D. Cunha, M. Friedl, L. Carvalho. **Bernstein Polynomial Processes for Continuous Time Change Detection** \[[paper](https://arxiv.org/abs/2504.17876)\] \[[code](https://github.com/daniel-s-cunha/BPP/)\] (submitted)

---
title: Papers (Applications)
---

Choi, Chi-Whan, Daniel Cunha, Christine Helfrich, and Simone V. Gill. "Factors contributing to whether or not people with obesity undergo bariatric surgery." Obesity Research & Clinical Practice 17, no. 6 (2023): 511-518.

Das, Rahul K., Leon Furchtgott, F-S. Ou, D. Swanson, B. Hayete, B. Harms, D. Cunha et al. "Causal modeling of CALGB/SWOG 80405 (Alliance) identifies primary (1°) side-related angiogenic drivers of metastatic colorectal cancer (mCRC)." Annals of Oncology 29 (2018): viii152.

Das, Rahul K., Leon Furchtgott, Jeffrey A. Meyerhardt, Andrew B. Nixon, Federico Innocenti, Daniel Cunha, Kelly Rich et al. "Causal modeling of CALGB 80405 (Alliance) to identify network drivers of metastatic colorectal cancer (CRC)." (2018): 3570-3570.
